### ISSUE TITLE
no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by DanBreton** [Tonire/ig-cachesim-ue4#1]
Hello,
Is there any steps to getting the submitted GUI Tool running? I get the following message when trying to run it (tried on multiple machines).
![image](https://user-images.githubusercontent.com/8995597/120528779-b9f09680-c3d3-11eb-8265-18b867803552.png)

Thanks!

**Comment by Tonire** [comment]
Oh, you are right!
I forgot to include some necessary dll files with the precompiled GUI tool.
Everything should work if you pull the latest commit from the repo.

Thanks!

**Comment by DanBreton** [comment]
Perfect, works now. Thanks!
